### ISSUE TITLE
Hosting this site for preview [ Freely host in github ]

### ISSUE THREAD

**Issue by maityamit** [PoojaJadhav03/Movie_Seat_Booking#1]
This site is good , But for preview please hosted this site in github free , the add the link on Readme File .

**Comment by PoojaJadhav03** [comment]
Yes, I know. Thanks for the information. I will do the required changes.

**Comment by PoojaJadhav03** [comment]
Kindly Check My Other Projects Also. So I can improve.

**Comment by maityamit** [comment]
> Kindly Check My Other Projects Also. So I can improve.

Absolutely , Ok . 👍
